In [ ]:

import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a*b

In [3]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\programdata\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>

In [4]:
who

a	 b	 np	 


#Numpy Arrays

In [9]:
import numpy as np
a = np.array([2.4,3.4,2,4])
a

array([2.4, 3.4, 2. , 4. ])

In [10]:
b = np.zeros(10,dtype=int) 
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
c=np.ones((2,3))
d=np.ones(10,dtype='float32')
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
e=np.full((2,3),9)
e

array([[9, 9, 9],
       [9, 9, 9]])

In [16]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [19]:
np.random.normal(0,1,(3,4))

array([[ 1.83779202,  1.01336113,  1.3245512 ,  0.53555665],
       [-0.65997823, -0.35295468, -0.24862993, -0.79967797],
       [ 1.17526077,  0.97745435, -1.94906857,  0.73050985]])

In [20]:
np.random.randint(0,10, (2,2))

array([[9, 0],
       [4, 2]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])